Repository vmware/vcf-sdk-go, pull requests merged in 2024-11, with the labels that each got.

#46 Add a custom template for response models
  cfg.yaml
  templates/client-with-responses.tmpl
  vcf/vcf.gen.go
Labels: needs-review

#48 chore: update dependabot
  .github/dependabot.yml
Labels: chore, dependencies, needs-review

#47 chore: update api specification for vcf-5.2.1
  CHANGELOG.md
  swagger.json
  vcf/vcf.gen.go
Labels: documentation, chore, needs-review
